### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by hekkelek** [marmoi/dcase2021_task1a_baseline#1]
Currently, the requirements cannot be installed using pip install -r requirements.txt (as suggested by README).

Also, it seems to have some compatibility issues too:

- The specified version of dcase_util relies on Tensorflow 1.x
- It does not have Keras version specified.

**Comment by marmoi** [comment]
I have changed the requirements.txt file. The problem is that currently dcase_util has to be installed manually  with "python setup.py develop" command from the development branch of the repository.

**Comment by hekkelek** [comment]
Thank you for the quick fix. Unfortunately, manually installing the develop branch of dcase_util still does not fix the issue. I attached the output log.
[output.txt](https://github.com/marmoi/dcase2021_task1a_baseline/files/6067007/output.txt)

**Comment by marmoi** [comment]
Sorry , we are still working on it. But this should fix the problem:

import tensorflow as tf
tf.compat.v1.ConfigProto

**Comment by marmoi** [comment]
The main files task1a.py and task1a_tflite.py have been updated, also the is a new release of the dcase_utils v0.2.17 which can be installed using "pip install dcase_util".
This should solve the incompatibility problems.

**Comment by hekkelek** [comment]
Thank you, it works now.
